North CLI: SONiC support
microsonic/goldstone-mgmt pull request #30
Opened 2020-09-02 13:25 UTC by cshivashgit

These changes have 
1. North CLI support for sonic-port, sonic-interface, sonic-vlan.
    Other than knows issues, CLIs work.
2. South sonic-interface is in C++.

2020-09-02 18:43 UTC, ishidawataru commented
@cshivashgit 

I had to change `mgmt.yaml` like below to load the SONiC YANG models properly.

```diff
-              command: ["/bin/sh","-c"]
-              args:
-                - sysrepoctl -s/var/lib/goldstone/yang/gs --install /var/lib/goldstone/yang/gs/goldstone-tai.yang,/var/lib/goldstone/yang/gs/goldstone-onlp.yang
-                - sysrepoctl -s /var/lib/goldstone/yang/sonic/common --install /var/lib/goldstone/yang/sonic/common/sonic-common.yang
-                - sysrepoctl -s /var/lib/goldstone/yang/sonic --install /var/lib/goldstone/yang/sonic/sonic-interface.yang,/var/lib/goldstone/yang/sonic/sonic-port.yang,/var/lib/goldstone/yang/sonic/sonic-portchannel.yang,/var/lib/goldstone/yang/sonic/sonic-vlan.yang
+              command: ["/bin/sh", "-c", "sysrepoctl -s /var/lib/goldstone/yang/gs --install /var/lib/goldstone/yang/gs/goldstone-tai.yang,/var/lib/goldstone/yang/gs/goldstone-onlp.yang && \
+sysrepoctl -s /var/lib/goldstone/yang/sonic/common --install /var/lib/goldstone/yang/sonic/common/sonic-common.yang && \
+sysrepoctl -s /var/lib/goldstone/yang/sonic --install /var/lib/goldstone/yang/sonic/sonic-interface.yang,/var/lib/goldstone/yang/sonic/sonic-port.yang,/var/lib/goldstone/yang/sonic/sonic-portchannel.yang,/var/lib/goldstone/yang/sonic/sonic-vlan.yang"]
```

After this change, I'm seeing the following error.

```bash
$ kubectl logs ds/gs-mgmt-sonic
libyang[0]: Missing required element "index" in "PORT_LIST". (path: /sonic-port:sonic-port/PORT/PORT_LIST[ifname='Ethernet1'])
gssouthd-sonic: /src/src/tree_data.c:6168: _lyd_free_node: Assertion `0' failed.
Aborted (core dumped)
```

Do you have any idea for the error?
I'm running usonic k8s pods ( https://github.com/microsonic/usonic/tree/master/k8s ) on my dev server.

```bash
$ kubectl get po
NAME                      READY   STATUS             RESTARTS   AGE
redis                     1/1     Running            0          32m
sonic-mgmt                1/1     Running            0          32m
usonic-cli                1/1     Running            0          32m
usonic-6f664b88c4-bv9bd   6/6     Running            0          32m
prep-gs-mgmt-c5n55        0/2     Completed          0          6m45s
gs-mgmt-onlp-nbz62        1/1     Running            0          6m45s
gs-mgmt-cli-pnfcw         1/1     Running            0          6m45s
gs-mgmt-np2-mvj42         1/1     Running            0          6m45s
gs-mgmt-tai-rdb44         2/2     Running            0          6m45s
gs-mgmt-sonic-nkqds       0/1     CrashLoopBackOff   5          6m45s
```

2020-09-02 18:54 UTC, ishidawataru commented
Also could you add a test case in CI to check SONiC south is working?

To do this, we need to run uSONiC pods in CI.

`kubectl create -f` can take a URL so, we can add

```
kubectl create -f https://raw.githubusercontent.com/microsonic/usonic/master/k8s/usonic.yaml
```

in [ci.yaml](https://github.com/microsonic/goldstone-mgmt/blob/master/.github/workflows/ci.yaml) for example.
It looks like there is no way to pass the whole directory (k8s) by USL, so you need to list all YAML file URLs.

2020-09-08 07:42 UTC, cshivashgit commented
@ishidawataru :
I tried multiple ways for including CI, seems timing issues. Can you suggest how to close this?

2020-09-08 15:44 UTC, ishidawataru commented
@cshivashgit  https://github.com/microsonic/goldstone-mgmt/runs/1084619005#step:12:27

`true` is not available in the CI env? Can you check?

2020-09-08 16:32 UTC, cshivashgit commented
> @cshivashgit https://github.com/microsonic/goldstone-mgmt/runs/1084619005#step:12:27
> 
> `true` is not available in the CI env? Can you check?

Issue was with "while" loop syntax in ci.yaml. 
CI has passed now.

2020-09-08 16:36 UTC, ishidawataru commented
ah thanks. actually, [ true ] should be just true.

2020-09-08 17:58 UTC, ishidawataru requested changes

2020-09-08 17:58 UTC, ishidawataru commented on src/north/cli/gscli/sonic.py
> +            self.tree = self.session.get_data_ly(self.XPATH)
use get_data() instead

2020-09-09 20:07 UTC, cshivashgit commented on src/north/cli/gscli/sonic.py
> +        self._set_hook = {}
If we remove them, we have below error when we go get/set operations.
AttributeError: 'Ifname' object has no attribute '_get_hook'
So we have retained them

2020-09-09 20:28 UTC, ishidawataru approved these changes
thanks for the update

2020-09-09 20:29 UTC, merged